# Generated by Django 5.2.7 on 2025-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shorturl',
            name='shortner_sh_is_expi_0607df_idx',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
